src/config/routes.rb
# Filaé is a tool supporting French Forensic Medical Units.
# Copyright (C) 2018-2025 infoPiiaf SARL
#
# This file is part of Filaé which is free software: you can redistribute it
# and/or modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, version 3.
#
# Filaé is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
Rails.application.routes.draw do
  concern :attachable do
    resources :attached_files do
      get "download", on: :member
      get "preview", on: :member
      get "list", on: :collection
    end
  end

  shallow do
    resources :intervention_domains, except: :show do
      resources :consultation_types, except: %i[index show] do
        resources :consultation_subtypes, except: %i[index show]
        resources :consultation_reasons, except: %i[index show]
        resources :appointments, except: :destroy do
          patch :take_charge, on: :member
          get :conclude, on: :member
          get :postpone, on: :member
          resource :certificate_preview, only: %i[show]
          concerns :attachable
          get "archives", on: :collection
          get "reset_filter", on: :collection
        end
      end
      resources :schedules do
        resources :time_slots
      end
      resources :flowing_consultations, except: :destroy do
        collection do
          get "list"
          get "last_updated"
          get "archives"
          get "reset_filter"
        end
        member do
          get "assign"
          get "validate"
          get "cancel"
          get "certificates"
          post "certificate"
        end
        concerns :attachable
      end
      get "appointments"
    end

    resources :calling_areas do
      resources :calling_institutions
    end

    resources :appointments, except: [:index, :destroy] do
      post "certificate", on: :member
      concerns :attachable
      resources :complementary_appointments, only: [:create, :destroy]
    end

    resources :certificates, only: [:edit, :update, :destroy] do
      member do
        patch :toggle_validation
        get :mail_form
        patch :send_by_mail
      end
      concerns :attachable
    end
    resources :certificate_templates do
      patch :toggle_activation, on: :member
      resources :master_documents, only: %i[create destroy] do
        get :download
      end
    end

    resources :calendar_days, only: %i[index show], id: ISO8601_DATE_REGEXP
    resources :consultation_types, only: %i[index create]
    resources :duty_periods, only: %i[edit update]
    resources :medical_files, only: %i[edit update]
    resources :patients, only: %i[index show edit update] do
      get :consultations, on: :member
      resources :duplicates, only: %i[show destroy]
    end
    resources :schedules, only: %i[create]
    resources :time_slots, only: %i[create]
    resources :users do
      patch "activate", on: :member
      get "deactivate", on: :member
    end

    namespace :settings do
      resource :certificate_layout, only: %i[edit update]
    end
  end

  resource :session, only: [:new, :create, :destroy]
  resource :search, only: [] do
    get "calling_institutions"
    get "patients"
  end
  resource :profile, only: [:show, :update]

  root to: "home#show"
end

src/app/models/certificate_template.rb
# Filaé is a tool supporting French Forensic Medical Units.
# Copyright (C) 2018-2025 infoPiiaf SARL
#
# This file is part of Filaé which is free software: you can redistribute it
# and/or modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, version 3.
#
# Filaé is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
class CertificateTemplate < ApplicationRecord
  has_many :certificate_templates_roles, dependent: :destroy
  has_many :roles, through: :certificate_templates_roles

  has_one :master_document, as: :attachable

  validates :title, presence: true

  scope :enabled, -> { where(disabled_at: nil) }
  scope :by_title, -> { order(title: :asc) }
  scope :for_user, ->(user) { joins(:roles).where(roles: user.role).distinct }
  scope :with_master_document, -> { joins(:master_document) }

  def disabled?
    disabled_at.present?
  end

  def enabled?
    !disabled?
  end

  def embedded?
    questionnaire.present?
  end
end

src/app/controllers/certificate_templates_controller.rb
# Filaé is a tool supporting French Forensic Medical Units.
# Copyright (C) 2018-2025 infoPiiaf SARL
#
# This file is part of Filaé which is free software: you can redistribute it
# and/or modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, version 3.
#
# Filaé is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
class CertificateTemplatesController < ApplicationController
  before_action :set_certificate_template, only: [:edit, :update, :toggle_activation,  :destroy]

  def index
    session[:show_disabled] = (params[:show_disabled] == "true" ? true : false)
    @certificate_templates = authorize policy_scope(CertificateTemplate).by_title
    @certificate_templates = (session[:show_disabled] ? @certificate_templates.all : @certificate_templates.enabled)
  end

  def new
    @certificate_template = authorize CertificateTemplate.new
  end

  def create
    sanitize_questionnaire
    @certificate_template = authorize CertificateTemplate.new(permitted_attributes(CertificateTemplate))

    if @certificate_template.save
      flash[:success] = t "flash.create.success"
      redirect_to certificate_templates_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    sanitize_questionnaire
    if @certificate_template.update(permitted_attributes(@certificate_template))
      flash[:success] = t "flash.update.success"
      redirect_to certificate_templates_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def toggle_activation
    disabled_at = @certificate_template.disabled_at
    if disabled_at.present?
      disabled_at = nil
      toggle_action = "Activation"
    else
      disabled_at = Time.zone.now
      toggle_action = "Désactivation"
    end
    if @certificate_template.update(disabled_at: disabled_at)
      flash[:success] = t "flash.action.success", action: toggle_action
    else
      flash[:danger] = t "flash.action.failure", action: toggle_action
    end
    redirect_to certificate_templates_path(show_disabled: session[:show_disabled])
  end

  def destroy
    if @certificate_template.destroy
      flash[:success] ||= t "flash.destroy.success"
    else
      flash[:danger] ||= t "flash.destroy.failure"
    end
    redirect_to certificate_templates_path
  end

  private

  def set_certificate_template
    @certificate_template = authorize CertificateTemplate.find(params[:id])
  end

  def sanitize_questionnaire
    if (questionnaire = params[:certificate_template][:questionnaire]).present?
      params[:certificate_template][:questionnaire] = JSON.parse(questionnaire.squish)
    end
  end
end

src/app/views/certificate_templates/_form.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
= simple_form_for @certificate_template do |f|
  = f.input :title
  .mt-4
    = f.association :roles, as: :check_boxes, label_method: :localized_title, value_method: :id, include_blank: false
  div data-controller="certificate-template-form"
    .form-check.form-switch.mb-3
      = check_box_tag :expert_mode, 'yes', false, class: ['form-check-input'], role: 'switch', data: { action: 'change->certificate-template-form#toggleExpertMode'}
      = label_tag :expert_mode, 'Mode expert', class: ['form-check-label']
    div hidden="hidden" data-certificate-template-form-target="expertMode"
      h3 Procédure recommandée
      ol
        li Copiez le contenu du champ texte ci-dessous
        li
          | Rendez-vous dans l'
          = link_to 'éditeur de questionnaire compatible', 'https://surveyjs.io/create-free-survey'
        li Collez ce que vous venez de copier dans leur onglet <code>JSON Editor</code>
        li Rendez-vous dans leur onglet <code>Designer</code>
        li Faites les changements souhaités
        li Copiez le contenu de leur onglet <code>JSON Editor</code>
        li Collez ce que vous venez de copier pour remplacer le contenu du champ texte ci-dessous.
      = f.input :questionnaire, input_html: { value: @certificate_template.questionnaire.to_json }

  = cancel_button certificate_templates_path
  = f.button :submit, 'Sauvegarder', class: ['btn-primary']

src/app/views/certificate_templates/edit.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
- breadcrumb :edit_certificate_template, @certificate_template

= render 'form'

src/app/views/certificate_templates/index.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
- breadcrumb :certificate_templates

h1
  = humanize_with_prefixed_count(CertificateTemplate, @certificate_templates.length)
  - if policy(CertificateTemplate).new?
    = custom_add_link new_certificate_template_path, title: "Nouveau modèle"

p = link_to 'Modifier le gabarit général', edit_settings_certificate_layout_path

- show_disabled = session[:show_disabled]
- action = (show_disabled ? 'Masquer' : 'Afficher')
p = link_to "#{action} les modèles désactivés", certificate_templates_path(show_disabled: !show_disabled)

#certificate-templates.accordion
  - @certificate_templates.each do |template|
    - master_document = template.master_document
    .accordion-item class=(template.enabled? ? '' : 'opacity-50')
      h2.accordion-header
        = button_tag type: 'button', class: ['accordion-button', 'collapsed'], data: { bs_toggle: 'collapse', bs_target: "#certificate-template-#{template.id}" } do
          .col = template.title
          .col
            = turbo_frame_tag dom_id(template, 'master_document_presence')
              = render partial: 'master_documents/master_document_presence', locals: { master_document: master_document }
            - if template.embedded?
              = fa_icon 'keyboard', title: 'Maquette embarquée'
          .col = template.roles.map(&:localized_title).join(', ')
          .actions.col
            - if policy(template).edit?
              = custom_edit_link edit_certificate_template_path(template)
            - if policy(template).toggle_activation?
              - if template.enabled?
                = link_to fa_icon('ban', title: 'Désactiver'), toggle_activation_certificate_template_path(template), method: :patch, class: ['text-danger'], data: { confirm: 'Êtes-vous sûr de vouloir désactiver cet élément ?' }
              - else
                = link_to fa_icon('circle-check', title: 'Activer'), toggle_activation_certificate_template_path(template), method: :patch, class: ['text-success'], data: { confirm: 'Êtes-vous sûr de vouloir activer cet élément ?' }
            - if policy(template).destroy?
              = custom_delete_link template
      .accordion-collapse.collapse id="certificate-template-#{template.id}" data-bs-parent='#certificate-templates'
        .accordion-body
            h3 Maquette à télécharger
            = turbo_frame_tag dom_id(template, 'master_document')
              = render partial: 'master_documents/master_document', locals: { master_document: master_document }
            = simple_form_for [template, MasterDocument.new], html: { 'data-controller': 'upload' } do |f|
              = f.input :file, as: :file, input_html: { data: { action: 'change->upload#uploadFiles' } }
              = f.button :submit, 'Sauvegarder', class: ['btn-primary'], data: { upload_target: 'submitButton' }, hidden: 'hidden'
            - if template.embedded?
              h3 Maquette embarquée
              = spinner
              .survey-form data-controller="survey-form" data-survey-form-questionnaire-value="#{template.questionnaire.to_json}"

src/app/views/certificate_templates/new.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
- breadcrumb :new_certificate_template

= render 'form'