src/config/routes.rb
# Filaé is a tool supporting French Forensic Medical Units.
# Copyright (C) 2018-2025 infoPiiaf SARL
#
# This file is part of Filaé which is free software: you can redistribute it
# and/or modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, version 3.
#
# Filaé is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
Rails.application.routes.draw do
  concern :attachable do
    resources :attached_files do
      get "download", on: :member
      get "preview", on: :member
      get "list", on: :collection
    end
  end

  shallow do
    resources :intervention_domains, except: :show do
      resources :consultation_types, except: %i[index show] do
        resources :consultation_subtypes, except: %i[index show]
        resources :consultation_reasons, except: %i[index show]
        resources :appointments, except: :destroy do
          patch :take_charge, on: :member
          get :conclude, on: :member
          get :postpone, on: :member
          resource :certificate_preview, only: %i[show]
          concerns :attachable
          get "archives", on: :collection
          get "reset_filter", on: :collection
        end
      end
      resources :schedules do
        resources :time_slots
      end
      resources :flowing_consultations, except: :destroy do
        collection do
          get "list"
          get "last_updated"
          get "archives"
          get "reset_filter"
        end
        member do
          get "assign"
          get "validate"
          get "cancel"
          get "certificates"
          post "certificate"
        end
        concerns :attachable
      end
      get "appointments"
    end

    resources :calling_areas do
      resources :calling_institutions
    end

    resources :appointments, except: [:index, :destroy] do
      post "certificate", on: :member
      concerns :attachable
      resources :complementary_appointments, only: [:create, :destroy]
    end

    resources :certificates, only: [:edit, :update, :destroy] do
      member do
        patch :toggle_validation
        get :mail_form
        patch :send_by_mail
      end
      concerns :attachable
    end
    resources :certificate_templates do
      patch :toggle_activation, on: :member
      resources :master_documents, only: %i[create destroy] do
        get :download
      end
    end

    resources :calendar_days, only: %i[index show], id: ISO8601_DATE_REGEXP
    resources :consultation_types, only: %i[index create]
    resources :duty_periods, only: %i[edit update]
    resources :medical_files, only: %i[edit update]
    resources :patients, only: %i[index show edit update] do
      get :consultations, on: :member
      resources :duplicates, only: %i[show destroy]
    end
    resources :schedules, only: %i[create]
    resources :time_slots, only: %i[create]
    resources :users do
      patch "activate", on: :member
      get "deactivate", on: :member
    end

    namespace :settings do
      resource :certificate_layout, only: %i[edit update]
    end
  end

  resource :session, only: [:new, :create, :destroy]
  resource :search, only: [] do
    get "calling_institutions"
    get "patients"
  end
  resource :profile, only: [:show, :update]

  root to: "home#show"
end

src/app/models/user.rb
# Filaé is a tool supporting French Forensic Medical Units.
# Copyright (C) 2018-2025 infoPiiaf SARL
#
# This file is part of Filaé which is free software: you can redistribute it
# and/or modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, version 3.
#
# Filaé is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
class User < ApplicationRecord
  has_secure_password
  has_many :appointments
  has_many :attached_files, as: :attachable

  belongs_to :role

  validates :identifier, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true
  validates :last_name, presence: true
  validates :password, confirmation: true, length: { minimum: 8 }, format: { with: /\A.*[A-Z]+.*\d+.*|.*\d+.*[A-Z]+.*\z/, message: :strength }, allow_nil: true

  scope :active, ->(disabled_after = Time.zone.now) { where(disabled_at: nil).or(where(disabled_at: disabled_after..)) }
  scope :by_deactivation, -> { order(disabled_at: :desc) }
  scope :by_name, -> { order(:last_name, :first_name) }
  scope :by_role, ->(role) { joins(:role).where(roles: { title: role}) }
  scope :of_matching_name, ->(name) { where("last_name ILIKE ?", "%#{name}%").or(self.where("first_name ILIKE ?", "%#{name}%")).distinct }

  # Activation
  def activation_status
    return "inactive" if inactive?
    return "deactivation-scheduled" if scheduled_for_deactivation?
    return "active" if active?
  end

  def active?
    !inactive?
  end

  def inactive?
    disabled_at&.past?
  end

  def scheduled_for_deactivation?
    disabled_at&.future?
  end

  def has_role?(title)
    self.role == Role.find_by_title(title)
  end

  def connected?
    true
  end

  def name
    "#{last_name} #{first_name}"
  end

  def abridged_name
    "#{first_name[0]}. #{last_name}"
  end

  def certificate_templates
    CertificateTemplate.for_user(self)
  end

  def role_title
    role.localized_title
  end

  def locale
    "fr"
  end

  def self.generate_secure_password
    SecureRandom.hex(10) + "F1L4É"
  end
end

src/app/controllers/users_controller.rb
# Filaé is a tool supporting French Forensic Medical Units.
# Copyright (C) 2018-2025 infoPiiaf SARL
#
# This file is part of Filaé which is free software: you can redistribute it
# and/or modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, version 3.
#
# Filaé is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :activate, :deactivate]

  def index
    authorize User
    @users = policy_scope(User).by_deactivation.by_name
  end

  def new
    @user = authorize User.new
  end

  def create
    sanitize_role
    @user = User.new(permitted_attributes(User))
    @user.password = User.generate_secure_password
    authorize @user

    if @user.save
      begin
        PasswordMailer.created(@user).deliver
        flash[:success] = t "flash.create.success"
        redirect_to users_path
      rescue => e
        @user.destroy
        logger.error "***** ERROR: #{e}"
        flash[:danger] = t "flash.create.failure"
        render :new, status: :unprocessable_entity
      end
    else
      flash[:danger] = t "flash.create.failure"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    sanitize_role
    if @user.update(permitted_attributes(@user))
      if @user.disabled_at.present?
        if @user.disabled_at > Time.zone.now
          flash[:success] = t ".deactivate.success.later", user_name: @user.name, deactivated_on: l(@user.disabled_at)
        else
          flash[:success] = t ".deactivate.success.now", user_name: @user.name
        end
      end
        flash[:success] ||= t "flash.update.success"
        redirect_to users_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def activate
    if @user.update(disabled_at: nil)
      flash[:success] = t ".success", user_name: @user.name
    else
      flash[:danger] = t ".failure", user_name: @user.name
    end
    redirect_to users_path
  end

  def deactivate
  end

  private

  def set_user
    @user = authorize User.find(params[:id])
  end

  def sanitize_role
    role_title = params[:user][:role_id]
    params[:user][:role_id] = Role.find_by_title(role_title).try(:id) || @user.role
  end
end

src/app/views/users/_form.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
= simple_form_for @user do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :identifier
  = f.input :email
  = f.association :role, label_method: :localized_title, value_method: :title, selected: @user.role&.title
  = f.button :submit, 'Sauvegarder', class: ['btn-primary']

src/app/views/users/deactivate.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
= simple_form_for @user do |f|
  = f.input :disabled_at
  = f.button :submit, 'Sauvegarder', class: ['btn-primary']

src/app/views/users/edit.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
- breadcrumb :edit_user, @user

= render 'form'

src/app/views/users/index.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
- breadcrumb :users

h1
  = humanize_with_prefixed_count(User, @users.length)
  - if policy(User).new?
    = custom_add_link new_user_path, title: 'Nouvel utilisateur' do
      = fa_icon "plus"

- Role.all.each do |role|
  - users = @users.where(role: role)
  div id="users-#{role.title}"
    h2 #{users.length} #{role.localized_title(users.length)}
    .row.row-cols-3
      - users.each do |user|
        .col-12.col-md-6.col-xl-4.my-3
          .card.h-100 class="#{user.activation_status}"
            .card-header
              h3.d-flex = user.name
            .card-body
              ul.list-group
                li.list-group-item.list-group-item-light.border-light
                  = fa_icon 'user', title: user.class.human_attribute_name(:identifier)
                  = user.identifier
                li.list-group-item.list-group-item-light.border-light
                  = fa_icon 'envelope', title: user.class.human_attribute_name(:email)
                  = user.email
            .card-footer
              = custom_edit_link edit_user_path(user)
              - unless user == current_user
                - if policy(user).deactivate?
                  = link_to fa_icon('ban', title: 'Désactiver'), deactivate_user_path(user), class: ['text-danger']
                  - if user.scheduled_for_deactivation?
                    = l user.disabled_at
                - if policy(user).activate?
                  - if user.inactive?
                    = fa_icon('ban', title: 'Désactivé')
                    = l user.disabled_at
                    = link_to fa_icon('circle-check', title: 'Réactiver'), activate_user_path(user), method: :patch, data: { confirm: "Êtes-vous sûr de vouloir réactiver #{user.name} ?" }, class: ['text-success']
                  - else
                    = link_to fa_icon('circle-check', title: 'Supprimer la désactivation'), activate_user_path(user), method: :patch, data: { confirm: "Êtes-vous sûr de vouloir supprimer la désactivation de #{user.name} ?" }, class: ['text-success']

src/app/views/users/new.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
- breadcrumb :new_user

= render 'form'