src/config/routes.rb
# Filaé is a tool supporting French Forensic Medical Units.
# Copyright (C) 2018-2025 infoPiiaf SARL
#
# This file is part of Filaé which is free software: you can redistribute it
# and/or modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, version 3.
#
# Filaé is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
Rails.application.routes.draw do
  concern :attachable do
    resources :attached_files do
      get "download", on: :member
      get "preview", on: :member
      get "list", on: :collection
    end
  end

  shallow do
    resources :intervention_domains, except: :show do
      resources :consultation_types, except: %i[index show] do
        resources :consultation_subtypes, except: %i[index show]
        resources :consultation_reasons, except: %i[index show]
        resources :appointments, except: :destroy do
          patch :take_charge, on: :member
          get :conclude, on: :member
          get :postpone, on: :member
          resource :certificate_preview, only: %i[show]
          concerns :attachable
          get "archives", on: :collection
          get "reset_filter", on: :collection
        end
      end
      resources :schedules do
        resources :time_slots
      end
      resources :flowing_consultations, except: :destroy do
        collection do
          get "list"
          get "last_updated"
          get "archives"
          get "reset_filter"
        end
        member do
          get "assign"
          get "validate"
          get "cancel"
          get "certificates"
          post "certificate"
        end
        concerns :attachable
      end
      get "appointments"
    end

    resources :calling_areas do
      resources :calling_institutions
    end

    resources :appointments, except: [:index, :destroy] do
      post "certificate", on: :member
      concerns :attachable
      resources :complementary_appointments, only: [:create, :destroy]
    end

    resources :certificates, only: [:edit, :update, :destroy] do
      member do
        patch :toggle_validation
        get :mail_form
        patch :send_by_mail
      end
      concerns :attachable
    end
    resources :certificate_templates do
      patch :toggle_activation, on: :member
      resources :master_documents, only: %i[create destroy] do
        get :download
      end
    end

    resources :calendar_days, only: %i[index show], id: ISO8601_DATE_REGEXP
    resources :consultation_types, only: %i[index create]
    resources :duty_periods, only: %i[edit update]
    resources :medical_files, only: %i[edit update]
    resources :patients, only: %i[index show edit update] do
      get :consultations, on: :member
      resources :duplicates, only: %i[show destroy]
    end
    resources :schedules, only: %i[create]
    resources :time_slots, only: %i[create]
    resources :users do
      patch "activate", on: :member
      get "deactivate", on: :member
    end

    namespace :settings do
      resource :certificate_layout, only: %i[edit update]
    end
  end

  resource :session, only: [:new, :create, :destroy]
  resource :search, only: [] do
    get "calling_institutions"
    get "patients"
  end
  resource :profile, only: [:show, :update]

  root to: "home#show"
end

src/app/models/schedule.rb
# Filaé is a tool supporting French Forensic Medical Units.
# Copyright (C) 2018-2025 infoPiiaf SARL
#
# This file is part of Filaé which is free software: you can redistribute it
# and/or modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, version 3.
#
# Filaé is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
class Schedule < ApplicationRecord
  belongs_to :intervention_domain
  has_many :time_slots, dependent: :destroy

  validates :activated_on, presence: true

  scope :on, ->(date) { where("activated_on <= ?", date).order("activated_on DESC").limit(1) }
  scope :for_consultation_type, ->(type) { type.intervention_domain.schedules }

  def self.duty_periods_for(consultation_type, date)
    schedule = self.for_consultation_type(consultation_type).on(date).first
    return [] unless schedule

    schedule.time_slots.where(consultation_type: consultation_type, week_day: date.cwday).map do |time_slot|
      DutyPeriod.find_or_create_by(time_slot: time_slot, scheduled_on: date)
    end
  end
end

src/app/controllers/schedules_controller.rb
# Filaé is a tool supporting French Forensic Medical Units.
# Copyright (C) 2018-2025 infoPiiaf SARL
#
# This file is part of Filaé which is free software: you can redistribute it
# and/or modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, version 3.
#
# Filaé is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
class SchedulesController < ApplicationController
  before_action :set_intervention_domain, only: [:new, :create]
  before_action :set_schedule, only: [:edit, :update, :destroy]

  def new
    @schedule = authorize @intervention_domain.schedules.build
  end

  def create
    @schedule = authorize @intervention_domain.schedules.new(permitted_attributes(Schedule))

    if @schedule.save
      flash[:success] = t "flash.create.success"
      redirect_to intervention_domains_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @consultation_types = schedule_consultation_types
  end

  def update
    if @schedule.update(permitted_attributes(@schedule))
      flash[:success] = t "flash.update.success"
      redirect_to intervention_domains_path
    else
      @consultation_types = schedule_consultation_types
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @schedule.destroy
      flash[:success] ||= t "flash.destroy.success"
    else
      flash[:danger] ||= t "flash.destroy.failure"
    end
    redirect_to intervention_domains_path
  end

  private

  def set_intervention_domain
    @intervention_domain = InterventionDomain.find_by(id: params[:intervention_domain_id])
  end

  def set_schedule
    @schedule = authorize Schedule.find(params[:id])
  end

  def schedule_consultation_types
    @schedule.intervention_domain.consultation_types.by_title
  end

end

src/app/views/schedules/_form.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
= simple_form_for [@intervention_domain, @schedule] do |f|
  = f.input :activated_on, html5: true, required: true

  = cancel_button intervention_domains_path
  = f.button :submit, 'Sauvegarder', class: ['btn-primary']

- if @schedule.persisted?
  table.table
    thead
      tr
        th Types de consultation
        th Lundi
        th Mardi
        th Mercredi
        th Jeudi
        th Vendredi
        th Samedi
        th Dimanche
      - @consultation_types.each do |type|
        tr
          td = type.title
          - (1..7).each do |day|
            td id="consultation-type-#{type.id}-day-#{day}"
              ul.list-group
              - @schedule.time_slots.each do |slot|
                - if slot.week_day == day && slot.consultation_type == type
                  li.list-group-item.d-flex.justify-content-between
                    = slot.display
                    .actions
                      = custom_edit_link edit_time_slot_path(slot)
                      = custom_delete_link slot
              = custom_add_link new_schedule_time_slot_path(@schedule, week_day: day, consultation_type_id: type.id), title: 'Nouveau créneau'

src/app/views/schedules/edit.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
- breadcrumb :edit_schedule, @schedule

= render 'form'

src/app/views/schedules/new.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
- breadcrumb :new_schedule, @intervention_domain

= render 'form'