src/config/routes.rb
# Filaé is a tool supporting French Forensic Medical Units.
# Copyright (C) 2018-2025 infoPiiaf SARL
#
# This file is part of Filaé which is free software: you can redistribute it
# and/or modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, version 3.
#
# Filaé is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
Rails.application.routes.draw do
  concern :attachable do
    resources :attached_files do
      get "download", on: :member
      get "preview", on: :member
      get "list", on: :collection
    end
  end

  shallow do
    resources :intervention_domains, except: :show do
      resources :consultation_types, except: %i[index show] do
        resources :consultation_subtypes, except: %i[index show]
        resources :consultation_reasons, except: %i[index show]
        resources :appointments, except: :destroy do
          patch :take_charge, on: :member
          get :conclude, on: :member
          get :postpone, on: :member
          resource :certificate_preview, only: %i[show]
          concerns :attachable
          get "archives", on: :collection
          get "reset_filter", on: :collection
        end
      end
      resources :schedules do
        resources :time_slots
      end
      resources :flowing_consultations, except: :destroy do
        collection do
          get "list"
          get "last_updated"
          get "archives"
          get "reset_filter"
        end
        member do
          get "assign"
          get "validate"
          get "cancel"
          get "certificates"
          post "certificate"
        end
        concerns :attachable
      end
      get "appointments"
    end

    resources :calling_areas do
      resources :calling_institutions
    end

    resources :appointments, except: [:index, :destroy] do
      post "certificate", on: :member
      concerns :attachable
      resources :complementary_appointments, only: [:create, :destroy]
    end

    resources :certificates, only: [:edit, :update, :destroy] do
      member do
        patch :toggle_validation
        get :mail_form
        patch :send_by_mail
      end
      concerns :attachable
    end
    resources :certificate_templates do
      patch :toggle_activation, on: :member
      resources :master_documents, only: %i[create destroy] do
        get :download
      end
    end

    resources :calendar_days, only: %i[index show], id: ISO8601_DATE_REGEXP
    resources :consultation_types, only: %i[index create]
    resources :duty_periods, only: %i[edit update]
    resources :medical_files, only: %i[edit update]
    resources :patients, only: %i[index show edit update] do
      get :consultations, on: :member
      resources :duplicates, only: %i[show destroy]
    end
    resources :schedules, only: %i[create]
    resources :time_slots, only: %i[create]
    resources :users do
      patch "activate", on: :member
      get "deactivate", on: :member
    end

    namespace :settings do
      resource :certificate_layout, only: %i[edit update]
    end
  end

  resource :session, only: [:new, :create, :destroy]
  resource :search, only: [] do
    get "calling_institutions"
    get "patients"
  end
  resource :profile, only: [:show, :update]

  root to: "home#show"
end

src/app/models/patient.rb
# Filaé is a tool supporting French Forensic Medical Units.
# Copyright (C) 2018-2025 infoPiiaf SARL
#
# This file is part of Filaé which is free software: you can redistribute it
# and/or modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, version 3.
#
# Filaé is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
class Patient < ApplicationRecord
  include Loggable
  include ActionView::Helpers::DateHelper

  enum :gender, { unknown: 0, woman: 1, man: 2}

  has_many :appointments
  has_many :flowing_consultations
  belongs_to :duplicated_patient, class_name: "Patient", optional: true
  belongs_to :probably_duplicated_patient, class_name: "Patient", optional: true

  default_scope { where(duplicated_patient_id: nil) }
  scope :fullname_asc, ->() { order(Arel.sql("LOWER(last_name) asc, LOWER(first_name) asc")) }
  scope :of_matching_lastname, ->(last_name) { where("last_name ILIKE ?", "#{last_name}%") }
  scope :of_matching_firstname, ->(first_name) { where("first_name ILIKE ?", "#{first_name}%") }
  scope :born_on_date, ->(date) { where(birthdate: date) }
  scope :born_on_year, ->(year) { where(birth_year: year).or(Patient.default_scoped.where("birthdate BETWEEN ? AND ?", Date.new(year.to_i,1,1), Date.new(year.to_i,12,31))) }

  validate :birthdate_within_birth_year
  validate :birthdate_from_string_valid?

  after_commit :touch_relevant_stuff, on: :update

  PAGINATIONS = [25, 50, 75, 100]
  paginates_per PAGINATIONS.min
  max_paginates_per PAGINATIONS.max

  def birthdate_from_string_valid?
    string_birthdate = attributes_before_type_cast["birthdate"].to_s
    string_birthdate.blank? || begin
      Date.parse(string_birthdate)
    rescue Date::Error
      errors.add(:birthdate, :invalid)
    end
  end

  def birthdate_within_birth_year
    if birth_year.present? && birthdate.present? && birth_year != birthdate.year
      errors.add(:birthdate, :must_match_birth_year)
    end
  end

  def aged_at(date)
    if birthdate.present?
      ActiveSupport::Duration.build(date.midday - birthdate.midday)
        .parts
        .slice(:years, :months)
        .map { |unit, val| I18n.t("datetime.distance_in_words.x_#{unit}", count: val) }
        .to_sentence
    elsif birth_year.present?
      oldest = ActiveSupport::Duration.build(date.midday - Date.new(birth_year, 1, 1).midday)
      youngest = ActiveSupport::Duration.build(date.midday - Date.new(birth_year, 12, 31).midday)
      lower_boundary, upper_boundary, unit = if oldest < 3.years
                                               [[youngest.in_months, 0].max, oldest.in_months, "months"]
                                             else
                                               [youngest.in_years, oldest.in_years, "years"]
                                             end
      "#{lower_boundary.floor}-#{I18n.t("datetime.distance_in_words.x_#{unit}", count: upper_boundary.floor)}"
    else
      '<abbr title="Non disponible">ND</abbr>'.html_safe
    end
  end

  def aged_at_now
    aged_at(Date.today)
  end

  def is_minor_on?(date)
    return nil unless date.is_a?(Date) && birthdate.present?
    age = date.year - birthdate.year
    age -= (date.month > birthdate.month || (date.month == birthdate.month && date.day >= birthdate.day) ? 0 : 1)
    age < 18
  end

  def human_birth
    birthdate ? I18n.l(birthdate) : birth_year
  end

  def fullname
    uppercase = last_name.blank? ? nil : last_name.upcase
    lowercase = first_name.blank? ? nil : first_name

    components = [uppercase, lowercase].compact
    if components.any?
      components.join(" ")
    else
      "Identité non-renseignée"
    end
  end

  def phone_numbers
    appointments.pluck(:patient_phone).compact.map { |phones| phones.split(",") }.flatten.map { |phone| phone.strip }.reject { |phone| phone.empty? }.uniq.join(", ")
  end

  def consultations_count
    appointments.count + flowing_consultations.count
  end

  def touch_relevant_stuff
    appointments.touch_all
    flowing_consultations.touch_all
  end

  def self.mark_all_duplicates!
    exact_duplicates(as_array: true).each do |duplicates|
      duplicates.delete((first_one = duplicates.min))
      where(id: duplicates).update_all(duplicated_patient_id: first_one)

      hand_over_consultations!(duplicates)
    end

    probable_duplicates(as_array: true).each do |duplicates|
      duplicates.delete((first_one = duplicates.min))
      where(id: duplicates).update_all(probably_duplicated_patient_id: first_one)
    end
  end

  def self.exact_duplicates as_array: false
    request = probable_duplicates.joins(:appointments).group("REGEXP_REPLACE(patient_phone, '[^[:digit:]]+', '', 'g')")
    as_array ? aggreg_ids(request) : request
  end

  def self.probable_duplicates as_array: false
    request = where.not(gender: nil).
      where.not(last_name: nil).
      where.not(first_name: nil).
      where.not(birthdate: nil).
      group(:gender, "LOWER(TRIM(last_name))", "LOWER(TRIM(first_name))", :birthdate).
      having("COUNT(DISTINCT patients.id) > 1")
    as_array ? aggreg_ids(request) : request
  end

  def self.aggreg_ids grouped
    grouped.pluck(Arel.sql("array_agg(patients.id)"));
  end

  def self.hand_over_consultations! duplicates
    ids_condition = ActiveRecord::Base.sanitize_sql_array(["p.id IN (?)", duplicates])

    hand_over_appointments_sql = <<~SQL
      UPDATE appointments
      SET original_patient_id = patient_id, patient_id = p.duplicated_patient_id
      FROM patients p
      WHERE patient_id = p.id
      AND #{ids_condition};
    SQL
    puts ActiveRecord::Base.connection.exec_query(hand_over_appointments_sql)

    hand_over_flowing_consultations_sql = <<~SQL
      UPDATE flowing_consultations
      SET original_patient_id = patient_id, patient_id = p.duplicated_patient_id
      FROM patients p
      WHERE patient_id = p.id
      AND #{ids_condition};
    SQL
    puts ActiveRecord::Base.connection.exec_query(hand_over_flowing_consultations_sql)
  end

  def self.rollback_all_duplicates!
    give_back_appointments_sql = <<~SQL
      UPDATE appointments
      SET patient_id = original_patient_id, original_patient_id = NULL
      WHERE original_patient_id IS NOT NULL
    SQL
    ActiveRecord::Base.connection.exec_query(give_back_appointments_sql)

    give_back_flowing_consultations_sql = <<~SQL
      UPDATE flowing_consultations
      SET patient_id = original_patient_id, original_patient_id = NULL
      WHERE original_patient_id IS NOT NULL
    SQL
    ActiveRecord::Base.connection.exec_query(give_back_flowing_consultations_sql)

    self.unscope(where: :duplicated_patient_id).update_all(duplicated_patient_id: nil, probably_duplicated_patient_id: nil)
  end
end

src/app/controllers/patients_controller.rb
# Filaé is a tool supporting French Forensic Medical Units.
# Copyright (C) 2018-2025 infoPiiaf SARL
#
# This file is part of Filaé which is free software: you can redistribute it
# and/or modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, version 3.
#
# Filaé is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[show edit update consultations]
  before_action :set_patientable, only: %i[update]
  before_action :pagination_params, only: :index
  before_action :filter_params, only: :index

  def index
    @patients = policy_scope(Patient).all
    # Filtering
    @patients = @patients.of_matching_lastname(@last_name_filter) if @last_name_filter.present?
    @patients = @patients.of_matching_firstname(@first_name_filter) if @first_name_filter.present?
    @patients = @patients.born_on_date(@birthdate_filter) if @birthdate_filter.present?
    @patients = @patients.born_on_year(@birth_year_filter) if @birth_year_filter.present?
    @patients = @patients.where.not(probably_duplicated_patient_id: nil) if @probable_duplicates.present?
    # Pagination
    @patients = authorize @patients.fullname_asc.page(@page).per(@size)
    @total_patients ||= Patient.count
  end

  def show
    render :show, layout: false
  end

  def edit
  end

  def update
    if @patient.update(permitted_attributes(@patient))
      if (sanitized_changes = @patient.previous_changes.except(:updated_at)).present?
        log_actions_for [Log::Action.new({ action: :updated, changes: sanitized_changes })], @patient
      end
      @partial = case request.referer
                 when /\/flowing_consultations/, /\/archives/
                   "patients/dropdown"
                 when /\/appointments/, /\/certificates/
                   "appointments/patient"
                 when /\/patients/
                   "patients/patient"
                 end
      flash.now[:success] = t "flash.update.success"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def consultations
  end

  private

  def set_patient
    @patient = authorize Patient.find(params[:id])
  end

  def set_patientable
    @patientable = if (patientable_id = params[:patient][:patientable_id].presence)
      referer_class.find(patientable_id)
    end
  end

  def pagination_params
    session[:pagination] ||= {}
    size = params[:size].to_i
    @size = (Patient::PAGINATIONS.include?(size) ? size : Patient.default_per_page)
    session[:pagination][:size] = @size
    page = params[:page].to_i
    @page = (Patient.page(page).per(@size).out_of_range? ? 1 : page)
    session[:pagination][:page] = @page
  end

  def filter_params
    @patient_filter = Patient.new

    if params[:patient]
      session[:patient_filter] ||= {}
      @patient_filter = Patient.new(permitted_attributes(Patient))
      @last_name_filter = session[:patient_filter][:last_name] = params[:patient][:last_name]
      @first_name_filter = session[:patient_filter][:first_name] = params[:patient][:first_name]
      @birthdate_filter = session[:patient_filter][:birthdate] = params[:patient][:birthdate]
      @birth_year_filter = session[:patient_filter][:birth_year] = params[:patient][:birth_year]
      @probable_duplicates = session[:patient_filter][:probably_duplicated_patient_id] =
        params[:patient][:probably_duplicated_patient_id]
    end
  end

  def referer_class
    case request.referer
    when /flowing_consultations/
      FlowingConsultation
    when /appointments/, /certificates/
      Appointment
    end
  end
end

src/app/views/patients/_appointments.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
div.mt-3
  h6.fw-bold Sur rendez-vous
  table.w-100
    caption.text-center = humanize_with_prefixed_count(Appointment, appointments.length)
    - appointments.each do |appointment|
      = render partial: 'appointments/appointment', locals: { appointment: appointment, hide_patient: true }

src/app/views/patients/_card.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
.card
  .card-header
    h2 = patient.fullname
  .card-body
    ul.list-group
      li.list-group-item
        = fa_icon 'venus-mars'
        = humanized_gender patient
      li.list-group-item
        = fa_icon 'calendar-alt'
        = patient.human_birth
      li.list-group-item
        = fa_icon 'clock', title: 'Âge actuel'
        = patient.aged_at_now

src/app/views/patients/_dropdown.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
- if (patient = patientable.patient)
  .dropdown id=dom_id(patient)
    button.btn.btn-light.dropdown-toggle type="button" data-bs-toggle="dropdown" aria-expanded="false"
      = fa_icon 'folder'
      = patient.fullname
    ul.dropdown-menu
      li.dropdown-item
        = fa_icon 'venus-mars'
        = humanized_gender patient
      li.dropdown-item
        = fa_icon 'calendar-alt'
        = patient.human_birth
      li.dropdown-item
        = fa_icon 'clock', title: 'Âge à la prise de rendez-vous'
        = patient.aged_at(patientable.created_at)
      li.dropdown-item
        - if policy(patient).edit?
          = custom_edit_link edit_patient_path(patient, patientable_id: patientable.id), title: 'Modifier le patient', format: :long, data: { turbo_frame: 'edit_patient' }

src/app/views/patients/_dynamic_form.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
= field_set_tag 'Patient', data: { \
    controller: "dynamic-patient-form",
    dynamic_patient_form_target: 'patientFieldset',
    } do
  div data-controller="autocomplete" data-autocomplete-url-value=patients_search_path role="combobox"
    = form.input :patient, label: false, input_html: { data: { autocomplete_target: 'input', dynamic_patient_form_target: 'patientSearchInput', action: 'input->dynamic-patient-form#updatePatientLastName'}, value: nil }
    = form.input :patient_id, as: :hidden, input_html: { \
      data: { \
        autocomplete_target: 'hidden',
        action: 'input->dynamic-patient-form#togglePatientId',
        dynamic_patient_form_target: 'patientIdInput',
      },
      value: patientable.patient&.id,
    }
    ul.list-group data-autocomplete-target="results"
  div data-dynamic-patient-form-target="existingPatientDiv"
    = button_tag fa_icon('eraser', title: 'Effacer'), type: 'button', data: { action: 'click->dynamic-patient-form#unsetPatientId'}, class: ['btn', 'bg-transparent']
    div data-dynamic-patient-form-target="existingPatientCard"
  div data-dynamic-patient-form-target="newPatientDiv"
    = form.simple_fields_for :patient do |p|
      = p.input :gender, collection: Patient.genders.map { |k,v| [t("gender.#{k}.normal"), k] }
      = p.input :last_name,
        input_html: { data: { dynamic_patient_form_target: 'patientLastNameInput' }}
      = p.input :first_name
      = p.input :birthdate, as: :date, html5: true, wrapper: :vertical_form,
        input_html: { data: { dynamic_patient_form_target: 'birthdateInput', action: 'keyup->dynamic-patient-form#checkBirthdate input->dynamic-patient-form#checkBirthdate' }}
  - if patientable.is_a? FlowingConsultation
    = form.input :concerns_minor
  - else
    = form.input :patient_phone

src/app/views/patients/_flowing_consultations.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
div.mt-3
  h6.fw-bold En flux
  table.FlowingConsultationsList.w-100
    caption.text-center = humanize_with_prefixed_count(FlowingConsultation, flowing_consultations.length)
    - flowing_consultations.each do |flowing_consultation|
      = render partial: 'flowing_consultations/item', locals: { item: flowing_consultation, read_only: true, hide_patient: true }

src/app/views/patients/_patient.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
tr id=dom_id(patient)
  td = humanized_gender(patient, abbreviated: true)
  td = patient.fullname
  td = patient.birthdate ? l(patient.birthdate) : patient.birth_year
  td = patient.phone_numbers
  td.text-info
    = link_to custom_link_name(:short, 'Historique des consultations', 'eye'), consultations_patient_path(patient), class: ['link-info'], data: { turbo_frame: 'consultations_listing'}
    = "(#{patient.consultations_count})"
  td
    - if policy(patient).edit?
      = custom_edit_link edit_patient_path(patient), data: { turbo_frame: 'edit_patient' }
    = render partial: 'logs', locals: { loggable: patient }
    - if policy(patient).edit?
      - if patient.probably_duplicated_patient_id
        = link_to "Doublon ?", duplicate_path(patient), class: "btn btn-sm btn-outline-warning", data: { turbo_frame: 'show_duplicate' }
      - elsif patient.duplicated_patient_id
        span.text-success Doublon fusionné ✓

src/app/views/patients/consultations.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
= turbo_frame_tag 'consultations_listing'
  .modal.fade data-controller="modal"
    .modal-dialog.modal-xl
      .modal-content
        .modal-header
          .modal-title
            h5 Historique des consultations

        .modal-body
          = render partial: 'card', locals: { patient: @patient}

          = render partial: 'appointments', locals: { appointments: @patient.appointments }

          = render partial: 'flowing_consultations', locals: { flowing_consultations: @patient.flowing_consultations }

        .modal-footer
          = button_tag 'Fermer', type: 'button', class: ['btn', 'btn-primary'], data: { 'bs-dismiss': 'modal' }
  = turbo_frame_tag 'attached_files'

src/app/views/patients/index.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
- breadcrumb :patients

h1 = "#{humanize_with_prefixed_count(Patient, @patients.length)} sur #{@total_patients}"

#lines-number-selector.btn-group
  - Patient::PAGINATIONS.each do |n|
    = link_to n.to_s, patients_path(request.query_parameters.merge({size: n, page: nil})), class: ['btn', (n == @patients.limit_value ? 'btn-primary' : 'btn-outline-primary')]

= simple_form_for @patient_filter, url: patients_path, method: :get, html: { id: 'filter', class: ['row'] } do |f|
  = f.input :last_name, wrapper_html: { class: ['col'] }
  = f.input :first_name, wrapper_html: { class: ['col'] }
  = f.input :birthdate, as: :date, html5: true, wrapper_html: { class: ['col'] }
  = f.input :birth_year, wrapper_html: { class: ['col'] }
  = f.input :probably_duplicated_patient_id, as: :boolean, checked_value: 1, unchecked_value: nil, wrapper_html: { class: ['col'] }
  .col
    = f.button :submit, 'Filtrer', class: ['btn-primary']
    = link_to 'Effacer', patients_path(size: session[:pagination][:size], page: nil), class: ['btn', 'btn-secondary']

= paginate @patients

= turbo_frame_tag 'edit_patient'
= turbo_frame_tag 'show_duplicate', target: "_top"
= turbo_frame_tag 'consultations_listing'

table.table
  thead
    tr
      th Genre
      th NOM Prénom
      th Naissance
      th Téléphones
      th Consultations
      th Actions
  tbody
    = render @patients

src/app/views/patients/show.html.slim
// Filaé is a tool supporting French Forensic Medical Units.
// Copyright (C) 2018-2025 infoPiiaf SARL
//
// This file is part of Filaé which is free software: you can redistribute it
// and/or modify it under the terms of the GNU Affero General Public License
// as published by the Free Software Foundation, version 3.
//
// Filaé is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
// License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>
//
= render partial: 'card', locals: { patient: @patient}